### ISSUE TITLE
CsvTableHeaderMatcher custom styles

### ISSUE THREAD

**Issue by akriger** [biegehydra/EasyCsv-Dotnet#4]
Is there a way to provide custom styles to the CsvTableHeaderMatcher? When there is a long string of text provided for a column, the Preview Information is to wide and makes the Csv Headers to small to read what they are matched to.

![image](https://github.com/biegehydra/EasyCsv-Dotnet/assets/12530743/e9b42e63-47b4-4db0-9f14-d9e1627dc4ba)

**Comment by biegehydra** [comment]
In this [commit](https://github.com/biegehydra/EasyCsv-Dotnet/commit/a98d5857d42bd9fe3ff392836de3f5b569d33447), which is live in version 2.0.0-beta8.2, I changed the default css to give the `Default Value` column and `Csv Headers` column a width of arround 220px. I also added this css to the preview information container.
```css
  .preview-information-container {
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3; /* Number of lines before truncation */
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 100%;
    }
```
The end result is something like this. If you would like to further configure the css, every `Td` and `Th` now has a unique css class that you can configure, e.g. ".preview-information-th" and ".preview-information-td"
![Screenshot_2](https://github.com/biegehydra/EasyCsv-Dotnet/assets/84036995/8f35dadb-8add-4faf-9064-cd591e933a55)

I reckon you might want an additional restriction on the width of the preview information th. Maybe something like:
```css
.preview-information-th {
        max-width: 300px;
}
```
